package:
  name: cephes
  version: "2016.03.11"

source:
  path: ../
  #git_url: https://github.com/poliastro/cephes
  #git_tag: master

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python

about:
  home: http://www.netlib.org/cephes/
  license: Public Domain
  summary: "Cephes C and C++ language special functions math library"
